ignore_images:
  - 2000mppSWDeathStar.gif
  - 2000mppphobos.gif
  - 100mppMacrossCapitalShips.gif
  - 100mppBabylon5.gif
  - 100mppSTStarbase.gif
  - 100mppB5Ships.gif
  - 10mppb5lowerscale.gif
  - 10mppb5eaearthforce1.gif
  - 10mppstsonacruiser.gif
  - 10mppb5iawhitestar.gif
  - 10mppstspecies8472.gif
  - 10mppswrebelfrigate.gif
  - 10mppzenscout.gif
  - 10mppmardukscout.gif
  - 10mppfarscapeships.gif
  - 10mppb5eaolympuscorvette.gif
  - 10mppexist.gif
  - 2mppexistSpaceStationA.gif
  - 2mppstsmallships.gif
  - 2mppswsmallships.gif
  - 2mppb5smallships.gif
  - 1mppSerenity.gif
  - 1mppb5smallships.gif
  - 1mppstsmallships.gif
  - 1mppswsmallships.gif
  - 1mppexistBoeing747.gif
  - 1mppexistbluewhale.gif
  - 1mppexistPeggysCoveLighthouse.gif
  - 1mppexiststealthfighter.gif
  - 1mppexist330tonminingtruck.gif
  - 1mppKingKong.gif
  - 10ppmhuman.gif
