ignore_images:
  - 100mppMacrossCapitalShips.gif
  - 100mppBabylon5.gif
  - 100mppSTStarbase.gif
  - 10mppb5lowerscale.gif
  - 10mppb5eaearthforce1.gif
  - 10mppstsonacruiser.gif
  - 10mppb5iawhitestar.gif
  - 10mppstspecies8472.gif
  - 2mppexistSpaceStationA.gif
  - 1mppSerenity.gif
  - 1mppb5smallships.gif
  - 1mppstsmallships.gif
  - 1mppswsmallships.gif
  - 1mppexistBoeing747.gif
